# Generated by Django 5.1 on 2024-08-19 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CulturalFacility",
            fields=[
                (
                    "esntl_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("mlsfc_nm", models.CharField(max_length=50)),
                ("fclty_nm", models.CharField(max_length=100)),
                ("ctprvn_nm", models.CharField(max_length=50)),
                ("signgu_nm", models.CharField(max_length=50)),
                ("fclty_road_nm_addr", models.CharField(max_length=200)),
                ("lnm_addr", models.CharField(max_length=200)),
                ("adit_dc", models.CharField(max_length=100, null=True)),
                ("latitude", models.CharField(default=1, max_length=200)),
                ("longitude", models.CharField(default=1, max_length=200)),
            ],
        ),
    ]
